const samplePropertyData = {
  properties: [
    {
      listing_agent: '1',
      headline: 'Just listed! Beautiful 2 bedroom apartment near the commons',
      slug: '12345-main-street',
      type: 'Apartment',
      mls_id: 'SR240012354',
      status: 'Active',
      listing_date: '2024-01-08T00:00:00.000Z',
      description:
        'This is a beautiful apartment located near the commons. It is a 2 bedroom apartment with a full kitchen and bathroom. It is available for list_price or lease_price rentals.',
      location: {
        street: '12345 Main Street',
        city: 'Valencia',
        state: 'CA',
        zipcode: '91355',
        neighborhood: 'Valencia Northbridge',
        coordinates: {
          latitude: 34.4138,
          longitude: -118.5539,
        },
      },
      beds: 2,
      baths: 1,
      square_feet: 1500,
      lot_size_units: 'square_feet',
      lot_size: {
        square_feet: 5500,
      },
      year_built: 1990,
      amenities: [
        'Wifi',
        'Full kitchen',
        'Washer & Dryer',
        'Free Parking',
        'Hot Tub',
        '24/7 Security',
        'Wheelchair Accessible',
        'Elevator Access',
        'Dishwasher',
        'Gym/Fitness Center',
        'Air Conditioning',
        'Balcony/Patio',
        'Smart TV',
        'Coffee Maker',
      ],
      price: {
        list_price: 100100,
      },
      commission_type: 'percentage',
      commission: {
        percentage: 2.5,
      },
      commission_description: 'Seller is offering 2.5% commission.',
      images: [
        '/images/sample-properties/a1.jpg',
        '/images/sample-properties/a2.jpg',
        '/images/sample-properties/a3.jpg',
      ],
      is_featured: false,
      created_at: '2024-01-01T00:00:00.000Z',
      updated_at: '2024-01-01T00:00:00.000Z',
    },
    {
      listing_agent: '2',
      headline: 'Spacious 4 Bedroom Home in Saugus with Pool',
      slug: '27890-plum-canyon-road',
      type: 'Single Family Home',
      mls_id: 'SR240045678',
      status: 'Active',
      listing_date: '2024-02-05T00:00:00.000Z',
      description:
        'A stunning 4-bedroom home in the heart of Saugus with a private pool and a spacious backyard. Perfect for families looking for a comfortable home.',
      location: {
        street: '27890 Plum Canyon Road',
        city: 'Saugus',
        state: 'CA',
        zipcode: '91350',
        neighborhood: 'Plum Canyon',
        coordinates: {
          latitude: 34.4672,
          longitude: -118.4991,
        },
      },
      beds: 4,
      baths: 3,
      square_feet: 2800,
      lot_size_units: 'square_feet',
      lot_size: {
        square_feet: 7500,
      },
      year_built: 2005,
      amenities: [
        'Swimming Pool',
        '2-Car Garage',
        'Fireplace',
        'Modern Kitchen',
        'Central AC',
        'Outdoor BBQ Area',
        'Smart Home Features',
      ],
      price: {
        list_price: 875000,
      },
      commission_type: 'percentage',
      commission: {
        percentage: 2.5,
      },
      commission_description: 'Buyer’s agent receives 2.5% commission.',
      images: [
        '/images/sample-properties/b1.jpg',
        '/images/sample-properties/b2.jpg',
        '/images/sample-properties/b3.jpg',
      ],
      is_featured: true,
      created_at: '2024-02-01T00:00:00.000Z',
      updated_at: '2024-02-01T00:00:00.000Z',
    },
    {
      listing_agent: '3',
      headline: 'Modern Townhouse in Valencia with Open Concept Design',
      slug: '25678-magic-mountain-parkway',
      type: 'Townhouse',
      mls_id: 'SR240078912',
      status: 'Pending',
      listing_date: '2024-02-20T00:00:00.000Z',
      description:
        'Gorgeous 3-bedroom, 2.5-bath townhouse with high ceilings and an open-concept design. Walking distance to shopping and dining.',
      location: {
        street: '25678 Magic Mountain Parkway',
        city: 'Valencia',
        state: 'CA',
        zipcode: '91355',
        neighborhood: 'Valencia Summit',
        coordinates: {
          latitude: 34.3985,
          longitude: -118.5563,
        },
      },
      beds: 3,
      baths: 2.5,
      square_feet: 1900,
      lot_size_units: 'square_feet',
      lot_size: {
        square_feet: 2000,
      },
      year_built: 2018,
      amenities: [
        'Gated Community',
        'Fitness Center',
        'Clubhouse',
        'Walk-In Closet',
        'Energy Efficient Appliances',
        'Attached Garage',
      ],
      price: {
        list_price: 695000,
      },
      commission_type: 'percentage',
      commission: {
        percentage: 2.25,
      },
      commission_description: 'Buyer’s agent commission is 2.25%.',
      images: [
        '/images/sample-properties/c1.jpg',
        '/images/sample-properties/c2.jpg',
        '/images/sample-properties/c3.jpg',
      ],
      is_featured: false,
      created_at: '2024-02-10T00:00:00.000Z',
      updated_at: '2024-02-10T00:00:00.000Z',
    },
    {
      listing_agent: '4',
      headline: 'Luxury Estate in Stevenson Ranch with Panoramic Views',
      slug: '26890-the-old-road',
      type: 'Luxury Home',
      mls_id: 'SR240098765',
      status: 'Active',
      listing_date: '2024-03-10T00:00:00.000Z',
      description:
        'A breathtaking 6-bedroom luxury estate with stunning panoramic views of Santa Clarita. Features a resort-style pool, home theater, and wine cellar.',
      location: {
        street: '26890 The Old Road',
        city: 'Stevenson Ranch',
        state: 'CA',
        zipcode: '91381',
        neighborhood: 'Southern Oaks',
        coordinates: {
          latitude: 34.3812,
          longitude: -118.5721,
        },
      },
      beds: 6,
      baths: 6,
      square_feet: 5500,
      lot_size_units: 'acres',
      lot_size: {
        acre: 1.2,
      },
      year_built: 2015,
      amenities: [
        'Infinity Pool',
        'Wine Cellar',
        'Gourmet Kitchen',
        'Home Theater',
        'Sauna',
        'Outdoor Fireplace',
        'Smart Home Technology',
      ],
      price: {
        list_price: 3250000,
      },
      commission_type: 'fixed',
      commission: {
        fixed: 50000,
      },
      commission_description: 'Flat commission of $50,000 to buyer’s agent.',
      images: [
        '/images/sample-properties/d1.jpg',
        '/images/sample-properties/d2.jpg',
        '/images/sample-properties/d3.jpg',
      ],
      is_featured: true,
      created_at: '2024-03-05T00:00:00.000Z',
      updated_at: '2024-03-05T00:00:00.000Z',
    },
    {
      listing_agent: '5',
      headline: 'Cozy 2-Bedroom Condo in Canyon Country',
      slug: '18901-soledad-canyon-road',
      type: 'Condo',
      mls_id: 'SR240112233',
      status: 'Active',
      listing_date: '2024-03-25T00:00:00.000Z',
      description:
        'Affordable 2-bedroom condo in a quiet gated community. Features a spacious balcony and access to a community pool and fitness center.',
      location: {
        street: '18901 Soledad Canyon Road',
        city: 'Canyon Country',
        state: 'CA',
        zipcode: '91351',
        neighborhood: 'Rainbow Glen',
        coordinates: {
          latitude: 34.4235,
          longitude: -118.4722,
        },
      },
      beds: 2,
      baths: 2,
      square_feet: 1200,
      lot_size_units: 'square_feet',
      lot_size: {
        square_feet: 3000,
      },
      year_built: 2000,
      amenities: ['Pool', 'Gated Community', 'Gym', 'Balcony'],
      price: {
        list_price: 425000,
      },
      commission_type: 'percentage',
      commission: {
        percentage: 2.5,
      },
      commission_description: '2.5% commission to buyer’s agent.',
      images: [
        '/images/sample-properties/e1.jpg',
        '/images/sample-properties/e2.jpg',
        '/images/sample-properties/e3.jpg',
      ],
      is_featured: false,
      created_at: '2024-03-20T00:00:00.000Z',
      updated_at: '2024-03-20T00:00:00.000Z',
    },
  ],
};

export default samplePropertyData;
