const samplePropertyData = {
  properties: [
    {
      listing_agent: '1',
      headline: 'Just listed! Beautiful 2 bedroom apartment near the commons',
      slug: '12345-main-street',
      type: 'Apartment',
      mls_id: 'SR240012354',
      status: 'Active',
      listing_date: '2024-01-08T00:00:00.000Z',
      description:
        'This is a beautiful apartment located near the commons. It is a 2 bedroom apartment with a full kitchen and bathroom. It is available for list_price or lease_price rentals.',
      location: {
        street: '12345 Main Street',
        city: 'Valencia',
        state: 'CA',
        zipcode: '91355',
        neighborhood: 'Valencia Northbridge',
        coordinates: {
          latitude: 34.4138,
          longitude: -118.5539,
        },
      },
      beds: 2,
      baths: 1,
      square_feet: 1500,
      lot_size_units: 'square_feet',
      lot_size: {
        square_feet: 5500,
        acre: null,
      },
      year_built: 1990,
      amenities: [
        'Wifi',
        'Full kitchen',
        'Washer & Dryer',
        'Free Parking',
        'Hot Tub',
        '24/7 Security',
        'Wheelchair Accessible',
        'Elevator Access',
        'Dishwasher',
        'Gym/Fitness Center',
        'Air Conditioning',
        'Balcony/Patio',
        'Smart TV',
        'Coffee Maker',
      ],
      price: {
        list_price: 100100,
        lease_price: null,
      },
      commission_type: 'percentage',
      commission: {
        percentage: 2.5,
        flat_fee: null,
      },
      commission_description: 'Seller is offering 2.5% commission.',
      images: [
        '/images/sample-properties/a1.jpg',
        '/images/sample-properties/a2.jpg',
        '/images/sample-properties/a3.jpg',
      ],
      is_featured: false,
      created_at: '2024-01-01T00:00:00.000Z',
      updated_at: '2024-01-01T00:00:00.000Z',
    },
    {
      listing_agent: '2',
      headline: 'Stunning 3 Bedroom Home with Pool in Canyon Country',
      slug: '67890-canyon-country-road',
      type: 'House',
      mls_id: 'SR240012355',
      status: 'Active',
      listing_date: '2024-01-12T00:00:00.000Z',
      description:
        'This stunning 3 bedroom, 2 bathroom home features a private pool and spa. Perfect for those hot summer days, it also includes a spacious backyard and is located in a quiet neighborhood.',
      location: {
        street: '67890 Canyon Country Road',
        city: 'Canyon Country',
        state: 'CA',
        zipcode: '91351',
        neighborhood: 'Canyon Country',
        coordinates: {
          latitude: 34.4101,
          longitude: -118.4907,
        },
      },
      beds: 3,
      baths: 2,
      square_feet: 1800,
      lot_size_units: 'square_feet',
      lot_size: {
        square_feet: 6500,
        acre: null,
      },
      year_built: 1995,
      amenities: [
        'Private Pool',
        'Spa',
        'Granite Countertops',
        'Wood Floors',
        'High Ceilings',
        'Fireplace',
        '2 Car Garage',
        'Backyard Patio',
        'Ceiling Fans',
        'Walk-in Closet',
      ],
      price: {
        list_price: 525000,
        lease_price: null,
      },
      commission_type: 'percentage',
      commission: {
        percentage: 3,
        flat_fee: null,
      },
      commission_description: 'Seller is offering 3% commission.',
      images: [
        '/images/sample-properties/b1.jpg',
        '/images/sample-properties/b2.jpg',
        '/images/sample-properties/b3.jpg',
      ],
      is_featured: true,
      created_at: '2024-01-05T00:00:00.000Z',
      updated_at: '2024-01-05T00:00:00.000Z',
    },
    {
      listing_agent: '3',
      headline: 'Modern 1 Bedroom Condo in Stevenson Ranch',
      slug: '24680-stevenson-ranch-road',
      type: 'Condo',
      mls_id: 'SR240012356',
      status: 'Active',
      listing_date: '2024-01-15T00:00:00.000Z',
      description:
        'This 1 bedroom, 1 bathroom condo is located in the highly sought-after Stevenson Ranch neighborhood. Features include modern appliances, spacious living areas, and community amenities.',
      location: {
        street: '24680 Stevenson Ranch Road',
        city: 'Stevenson Ranch',
        state: 'CA',
        zipcode: '91381',
        neighborhood: 'Stevenson Ranch',
        coordinates: {
          latitude: 34.3872,
          longitude: -118.5635,
        },
      },
      beds: 1,
      baths: 1,
      square_feet: 800,
      lot_size_units: 'square_feet',
      lot_size: {
        square_feet: 3000,
        acre: null,
      },
      year_built: 2000,
      amenities: [
        'Community Pool',
        'Gym/Fitness Center',
        'Clubhouse',
        'Modern Kitchen',
        'Stainless Steel Appliances',
        'Balcony',
        'Walk-in Closet',
        'Central Air Conditioning',
      ],
      price: {
        list_price: 315000,
        lease_price: null,
      },
      commission_type: 'percentage',
      commission: {
        percentage: 2.5,
        flat_fee: null,
      },
      commission_description: 'Seller is offering 2.5% commission.',
      images: [
        '/images/sample-properties/c1.jpg',
        '/images/sample-properties/c2.jpg',
        '/images/sample-properties/c3.jpg',
      ],
      is_featured: false,
      created_at: '2024-01-10T00:00:00.000Z',
      updated_at: '2024-01-10T00:00:00.000Z',
    },
    {
      listing_agent: '4',
      headline: 'Charming 4 Bedroom Home in Newhall with Large Backyard',
      slug: '13579-newhall-avenue',
      type: 'Single Family Residence',
      mls_id: 'SR240012357',
      status: 'Active',
      listing_date: '2024-01-20T00:00:00.000Z',
      description:
        'This beautiful 4 bedroom, 3 bathroom home is located in the heart of Newhall. It features a spacious backyard, updated kitchen, and is close to schools and shopping.',
      location: {
        street: '13579 Newhall Avenue',
        city: 'Newhall',
        state: 'CA',
        zipcode: '91321',
        neighborhood: 'Newhall',
        coordinates: {
          latitude: 34.3798,
          longitude: -118.5306,
        },
      },
      beds: 4,
      baths: 3,
      square_feet: 2200,
      lot_size_units: 'square_feet',
      lot_size: {
        square_feet: 8000,
        acre: null,
      },
      year_built: 1998,
      amenities: [
        'Large Backyard',
        'Updated Kitchen',
        'Granite Countertops',
        'Wood Floors',
        'Fireplace',
        'Walk-in Closet',
        '2 Car Garage',
        'Patio Area',
        'Ceiling Fans',
        'Central Heating & AC',
      ],
      price: {
        list_price: 625000,
        lease_price: null,
      },
      commission_type: 'percentage',
      commission: {
        percentage: 3,
        flat_fee: null,
      },
      commission_description: 'Seller is offering 3% commission.',
      images: [
        '/images/sample-properties/d1.jpg',
        '/images/sample-properties/d2.jpg',
        '/images/sample-properties/d3.jpg',
      ],
      is_featured: true,
      created_at: '2024-01-15T00:00:00.000Z',
      updated_at: '2024-01-15T00:00:00.000Z',
    },
    {
      listing_agent: '5',
      headline: 'Spacious 3 Bedroom Townhouse in Saugus with Mountain Views',
      slug: '98765-saugus-avenue',
      type: 'Townhouse',
      mls_id: 'SR240012358',
      status: 'Active',
      listing_date: '2024-01-25T00:00:00.000Z',
      description:
        'This spacious 3 bedroom, 2.5 bathroom townhouse in Saugus offers breathtaking mountain views, a large living space, and a private 2-car garage. Perfect for families!',
      location: {
        street: '98765 Saugus Avenue',
        city: 'Saugus',
        state: 'CA',
        zipcode: '91350',
        neighborhood: 'Saugus',
        coordinates: {
          latitude: 34.3792,
          longitude: -118.4978,
        },
      },
      beds: 3,
      baths: 2.5,
      square_feet: 1700,
      lot_size_units: 'square_feet',
      lot_size: {
        square_feet: 6000,
        acre: null,
      },
      year_built: 2005,
      amenities: [
        'Mountain Views',
        'Private Garage',
        'Updated Kitchen',
        'Fireplace',
        'Balcony',
        'Walk-in Closet',
        'Ceiling Fans',
        'Community Pool',
        'Patio',
        'Gym/Fitness Center',
      ],
      price: {
        list_price: 460000,
        lease_price: null,
      },
      commission_type: 'percentage',
      commission: {
        percentage: 3,
        flat_fee: null,
      },
      commission_description: 'Seller is offering 3% commission.',
      images: [
        '/images/sample-properties/e1.jpg',
        '/images/sample-properties/e2.jpg',
        '/images/sample-properties/e3.jpg',
      ],
      is_featured: false,
      created_at: '2024-01-18T00:00:00.000Z',
      updated_at: '2024-01-18T00:00:00.000Z',
    },
    {
      listing_agent: '6',
      headline: 'Cozy 2 Bedroom Condo with Pool in Stevenson Ranch',
      slug: '54321-stevenson-ranch-road',
      type: 'Condo',
      mls_id: 'SR240012359',
      status: 'Active',
      listing_date: '2024-01-30T00:00:00.000Z',
      description:
        'This cozy 2 bedroom, 2 bathroom condo features community pool access, modern appliances, and a peaceful atmosphere. Located in a prime Stevenson Ranch neighborhood.',
      location: {
        street: '54321 Stevenson Ranch Road',
        city: 'Stevenson Ranch',
        state: 'CA',
        zipcode: '91381',
        neighborhood: 'Stevenson Ranch',
        coordinates: {
          latitude: 34.3811,
          longitude: -118.566,
        },
      },
      beds: 2,
      baths: 2,
      square_feet: 950,
      lot_size_units: 'square_feet',
      lot_size: {
        square_feet: 2000,
        acre: null,
      },
      year_built: 2010,
      amenities: [
        'Community Pool',
        'Modern Appliances',
        'Ceiling Fans',
        'Central AC',
        'Walk-in Closet',
        'Balcony',
        'Dishwasher',
        'Washer & Dryer',
      ],
      price: {
        list_price: 380000,
        lease_price: null,
      },
      commission_type: 'percentage',
      commission: {
        percentage: 2.5,
        flat_fee: null,
      },
      commission_description: 'Seller is offering 2.5% commission.',
      images: [
        '/images/sample-properties/f1.jpg',
        '/images/sample-properties/f2.jpg',
        '/images/sample-properties/f3.jpg',
      ],
      is_featured: false,
      created_at: '2024-01-22T00:00:00.000Z',
      updated_at: '2024-01-22T00:00:00.000Z',
    },
  ],
};

export default samplePropertyData;
